### ISSUE TITLE
Syncer - merge of L1 and L2 transactions

### ISSUE THREAD

**Issue by szynwelski** [warp-contracts/sequencer#20]
Warp Contracts should support both transactions that go through the sequencer (L2) and transactions that were sent to Arweave without going through the sequencer (L1). L2 transactions should be processed as soon as they are placed in the sequencer chain.  L1 transactions must be processed with some delay due to the possibility of a fork.

Current solution sorts transactions based on the `sort_key` value, which first takes into account the height of the current block in Arweave and then the timestamp of the transaction's reception by the centralized sequencer (for L1 transactions, this value is 0). Details of this mechanism can be found [here](https://docs.warp.cc/docs/sdk/advanced/bundled-interaction#how-it-works).

In the new solution, we need to merge transactions from two blockchains, so we can no longer take into account the block height, which is different for these two chains. Fortunately, both blockchains validate block timestamps, making them trustworthy values that can serve as a basis for merging these two chains. Therefore, in the new solution, the order of transactions will be determined based on the block timestamp and then the transaction index in the transaction list of this block. However, for L1 transactions, we add a certain delay (e.g., 40 minutes) to the block timestamp as protection against forks.

Transactions retrieved and merged by the Syncer are then sent to the [Warp Gateway](https://docs.warp.cc/docs/gateway/overview) and then to the [Warp D.R.E. nodes](https://docs.warp.cc/docs/dre/overview).

**Comment by szynwelski** [comment]
Alternative to the above solution, where merging occurs in a central Syncer, is to move the merging process to the network of sequencers.

#### Assumptions required for this solution:
- Periodically, between L2 transactions, we insert an L1 block.
- L1 block should have enough delay to make the probability of forking negligible.
- Let's assume the delay is 1 hour (approximately 30 blocks).
- With this delay, each sequencer node will have enough time to:
  - Fetch the Arweave block from an hour ago and perform initial validation on it.
  - This block will not change in the future (no fork will occur).
  - Each sequencer node will have the same downloaded block.
  - In case of network issues, they can retry fetching the block.
  - As a precaution, they can query multiple Arweave nodes to ensure they all provide the same response.

#### With the above assumptions, the following solution can be safely implemented:
- Once in a while (about 2 minutes), a block in the sequencer network will contain a transaction with information about an Arweave block.
- This information will include: block height, timestamp, and a list of interactions contained in the Arweave block.
- When a proposer creates a new sequencer block, they must check whether this block is the first one to meet the condition: the timestamp of the previous sequencer block is one hour later than the timestamp of the first Arweave block not uploaded to the sequencer network.
- If this condition is met, the proposer adds a transaction with information about the Arweave block to the block proposal (the addition will take place in the `PrepareProposal` method of the [ABCI++](https://docs.cometbft.com/v0.37/spec/abci/) interface).
- Validators who vote for the block proposal check whether:
  - The above condition is met.
  - The Arweave block information matches the block they fetched.

#### Calculating the sort key:
- Thanks to the presence of information about Arweave blocks in the network, sequencer nodes can calculate the `sort_key` and `last_sort_key` for each interaction.
- These values can be compatible with the currently used format (see [documentation](https://docs.warp.cc/docs/sdk/advanced/bundled-interaction#how-it-works)).
- For L2 interactions, it would be a triplet:
  - The height of the last Arweave block, whose information is in the sequencer network.
  - The height of the Cosmos block.
  - The index of the interaction in the Cosmos block.
- L1 interactions would have the existing value: (Arweave block height, zero, and a hash according to the [SmartWeave](https://docs.warp.cc/docs/sdk/advanced/smartweave-protocol) protocol).
- The `sort_key` and `last_sort_key` values would be additional fields in the `MsgDataItem` message.
- When such a message enters the mempool, it initially has empty values for these two fields.
- When a proposer creates a block proposal, these fields are calculated and set in the transaction messages during the `PrepareProposal` method call.
- Other validators verify whether these values have been calculated correctly.

#### Advantages of the above solution:
- Merging and calculating sort keys occur in a decentralized network (so is verified by other nodes).
- There is no single point of failure for these functionalities.
- If someone doesn't want to trust centralized elements (like Gateway or Syncer in the previous solution), they can calculate the contract state evaluation based on sequencer blocks or, with some delay, on Arweave blocks (see functionality of relayer #13).
- If the assumptions about the determinism of Arweave blocks from an hour ago are met, there is no threat to the consensus in the sequencer network.

**Comment by janekolszak** [comment]
Additional time interval is needed. In this example: 1h delay = 50' delay added to avoid forks in Arweave + 10' timeout for downloading and verifying a block

**Comment by szynwelski** [comment]
### Implementation plan of the above functionality.

#### Storage for Arweave block height and sort keys of contracts
- Add storage for the last Arweave block height added to the network (probably using the command: `ignite scaffold single`). This storage will allow calculating the `SortKey` for new interactions.
- Add storage that, for each contract, stores the sort key of the last interaction (probably using the command: `ignite scaffold map`). This storage will allow calculating the `LastSortKey` for new interactions.

#### Fields `SortKey` and `LastSortKey`
- We are adding fields `SortKey` and `LastSortKey` of type `string` to `MsgDataItem`.
- During broadcasting and adding to the mempool, these fields are empty (i.e., when the `BroadcastDataItem` function is called).
- Their values are set in the `PrepareProposal` method, once the block proposal is prepared, and the transaction order in the block is known.
- `SortKey` is calculated as a triplet:
  - Arweave block height retrieved from storage
  - The height of the block we are currently proposing
  - The index of the interaction in the proposed block
- `LastSortKey` is calculated based on the map from the storage.
- While processing a data item (in the file `msg_server_data_item.go`), we should check if its `LastSortKey` matches what we have in storage for that contract. If it matches, we set the new `SortKey`; if it doesn't, we throw an error.

**Comment by szynwelski** [comment]
Basic issue functionality implemented in the following pull requests:
