### ISSUE TITLE
Performance optimization

### ISSUE THREAD

**Issue by szynwelski** [warp-contracts/sequencer#63]
### CPU
![profile007](https://github.com/warp-contracts/sequencer/assets/18469878/48864379-5fba-4495-be40-4e582abb0de1)
### Delay
![profile008](https://github.com/warp-contracts/sequencer/assets/18469878/2786376b-9c04-4dbf-a058-11526b8ac0ac)
### Space used
![profile009](https://github.com/warp-contracts/sequencer/assets/18469878/f5fc35fe-0434-4f56-8073-a8fe2982af20)

**Comment by janekolszak** [comment]
Tested with v0.0.29, looked the same
![block](https://github.com/warp-contracts/sequencer/assets/3087849/6e2cbf3f-9668-4b1d-b49f-635269ecbdb0)
![goroutine](https://github.com/warp-contracts/sequencer/assets/3087849/1e9bc6f9-73d3-4190-8aee-70d15053f9ac)
![heap](https://github.com/warp-contracts/sequencer/assets/3087849/8d11ecee-13cb-49d7-9f98-bd90c86f9628)
![profile](https://github.com/warp-contracts/sequencer/assets/3087849/dea488f1-8a62-4b6a-9221-dfc6ab9aac76)

**Comment by szynwelski** [comment]
Limiting data item validation during `processProposal` and `reCheck`: #66

**Comment by szynwelski** [comment]
Optimizing validation of data items by AnteHandler: #69

**Comment by szynwelski** [comment]
Optimization of transaction validation during the execution of the `recheckTx` method, which is triggered on transactions in the mempool after block commit: #72

**Comment by szynwelski** [comment]
Introduction of parallel transaction validation: #75

**Comment by szynwelski** [comment]
Faster implementation of the nonce retrieval endpoint: #83

**Comment by szynwelski** [comment]
No further optimizations are required at this time.
